### ISSUE TITLE
does not switch state wet_protection

### ISSUE THREAD

**Issue by 4ertik131** [syssi/xiaomi_airpurifier#106]
![IMG_20201116_164909](https://user-images.githubusercontent.com/73563169/99260065-f986d500-282b-11eb-9892-e62aa30058a4.jpg)
    
good evening !
it took me a while to upgrade to a new python version.

i created a switch wet_protection one ok doesn't work! does not switch state.

 ```  
xiaomi_airpurifier_wet_protection:
        friendly_name: "wet_protection"
        value_template: "{{ is_state_attr('fan.xiaomi_air_humidifier', 'wet_protection', true) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_wet_protection_on
          data:
            entity_id: fan.xiaomi_air_humidifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_wet_protection_off
          data:
            entity_id: fan.xiaomi_air_humidifier
        icon_template: "mdi:lightbulb-outline"

```

Am I wrong in the code?
