### ISSUE TITLE
service not found

### ISSUE THREAD

**Issue by fedottt** [syssi/xiaomi_airpurifier#113]
in additional (three dots) i have some buttons to control humidifier
but, when i click on some of that buttons, i take error: "failed to call service fan/xiaomi_miio_set_led_off. Service not found"
this error not on all buttons.
on **deerma.humidifier.mjjsq** is five elements to control: power, target hum, speed, sound, light
work only power and speed.  
maybe i doing something wrong?

configuration.yaml
```
fan:
  - platform: xiaomi_miio_airpurifier
    host: 192.168.1.49
    name: hum-2
    token: *token*
    model: deerma.humidifier.mjjsq
```
