### ISSUE TITLE
Support zhimi.airpurifier.mb4

### ISSUE THREAD

**Issue by MarcE85** [syssi/xiaomi_airpurifier#117]
Hey,

could you please add support for the Xiaomi Air purifier C3.
miiocli info attached:

```
Model: zhimi.airpurifier.mb4
Hardware version: esp32
Firmware version: 2.0.8
```

Regards Marc

**Comment by arturdobo** [comment]
@MarcE85 I received this air purifier couple of days ago and now I'm working on that

**Comment by arturdobo** [comment]
It turned out to be a little bit more difficult than I thought. First, the following [issue](https://github.com/rytilahti/python-miio/issues/888) needs to be resolved in `python-miio`

**Comment by asiersan** [comment]
Im interested un this integration too

**Comment by arturdobo** [comment]
https://github.com/rytilahti/python-miio/pull/899 has been created in `python-miio`

**Comment by TomStarren** [comment]
I'm also interested in this integration, any ideas in which timeframe this can be added?

**Comment by arturdobo** [comment]
@TomStarren as I mentioned above, first PR in `python-miio` needs to be merged. So it's good to ask there about reviewing status ;)

**Comment by arturdobo** [comment]
https://github.com/rytilahti/python-miio/pull/899 has been merged

**Comment by asiersan** [comment]
> [rytilahti/python-miio#899](https://github.com/rytilahti/python-miio/pull/899) has been merged

So now??

**Comment by arturdobo** [comment]
Once the newest version of `python-miio` is released, integration with 3C in this repo can be added 😉  

@syssi What's the relation between this repo and the same code in the HA repo? I saw there is some problem regarding adding new integrations with Xiaomi devices to HA using the old way. Could you more details? Is there any work in progress to improve that?

**Comment by syssi** [comment]
@arturdobo Take a look at this paragraph: https://github.com/syssi/xiaomi_airpurifier/#what-is-the-difference-between-this-custom-component-and-the-one-in-home-assistant-core

One point is missing: We are abusing attributes to provide the values of some properties (temperature, humiditiy, etc.) at the moment. This isn't allowed anymore. A device (the Air Purifier) must register multiple entities (fan, sensor, binary_sensor, switch, etc.) now. The `xiaomi_miio` component must be refactored. @starkillerOG is doing some great work here already (https://github.com/rytilahti/python-miio/issues/929). I'm tryinng to provide as much support as I can.

**Comment by syssi** [comment]
Feel free to provide a pull request for this custom component as first step to support your device. I'm trying to refactor the component to be merged as official HA component again some day.

**Comment by asiersan** [comment]
Any update?

**Comment by arturdobo** [comment]
nope

**Comment by nefsolive** [comment]
We need wait  update "zhimi.airpurifier.mb4"

**Comment by arturdobo** [comment]
Things a little bit changed and now it'd be better to wait until [this](https://github.com/home-assistant/core/pull/46866/files) is merged. Then I believe the newest version of `python-miio` will be released so adding a new device should be easier.

**Comment by nefsolive** [comment]
As soon as it becomes possible to work zhimi.airpurifier.mb4, I also hope to find a possible plugin for domoticz

**Comment by arturdobo** [comment]
Does domoticz uses `python-miio` directly, or is there any middleware?

**Comment by nefsolive** [comment]
Like this on https://github.com/xiaoyao9184/DomoticzXiaomiPlugins and this plugin use python-miio. But i think, they need be updated too!

**Comment by arturdobo** [comment]
At the first glance, it looks like only the only thing you need is to `python-miio` be released. Maybe it'd be good to open an issue regarding that.

**Comment by nefsolive** [comment]
Yes arturdobo! Maybe that's it. I'll wait for the update. May it be soon, i hope.

**Comment by postscriptumpl** [comment]
@arturdobo support for 3C is already implemented in python-miio. Any chance to expect this functionality here soon?
Thanks for the support!

**Comment by arturdobo** [comment]
@postscriptumpl yeah, I know, because I  was the author 😆  I've just created this following issue https://github.com/rytilahti/python-miio/issues/969

**Comment by postscriptumpl** [comment]
Ups...that was not very smart of me 🙈 Anyway I keep fingers crossed 🤞🏻😁

**Comment by postscriptumpl** [comment]
@arturdobo a shy reminder ☺️ python released 😁

**Comment by arturdobo** [comment]
Chase me, if it's not done till end of this week

**Comment by arturdobo** [comment]
@postscriptumpl it looks like [PR](https://github.com/home-assistant/core/pull/47924) for adding 3C is already there. So I'll add support for `Qingping Air Monitor Lite` then

**Comment by postscriptumpl** [comment]
@arturdobo do You think that it's going to be released with the newest update of HA? Or how it works?

**Comment by arturdobo** [comment]
No idea TBH

**Comment by bartohz** [comment]
Any updates on this? Seems to be added to `python-miio`

**Comment by nefsolive** [comment]
@bartohz its domoticz you have?

**Comment by bartohz** [comment]
> @bartohz its domoticz you have?

No, Home Assistant.

**Comment by RenanAz** [comment]
Hi there team! Thanks for the awesome work so far :) 
Any updates on the 3C? If you need someone to help out testing this, the devices is here ready to go.
Thanks again

**Comment by suarezcp87** [comment]
hello with this integration works https://github.com/al-one/hass-xiaomi-miot
![Новый точечный рисунок (3)](https://user-images.githubusercontent.com/78756329/115070555-c1c8aa00-9efd-11eb-95b9-ed459e5721e5.jpg)
![Новый точечный рисунок](https://user-images.githubusercontent.com/78756329/115070773-0b18f980-9efe-11eb-843f-5c6481c9a853.jpg)

**Comment by asiersan** [comment]
Yes is working, but not in local only in cloud

**Comment by bartohz** [comment]
> hello with this integration works https://github.com/al-one/hass-xiaomi-miot
> ![Новый точечный рисунок (3)](https://user-images.githubusercontent.com/78756329/115070555-c1c8aa00-9efd-11eb-95b9-ed459e5721e5.jpg)
> ![Новый точечный рисунок](https://user-images.githubusercontent.com/78756329/115070773-0b18f980-9efe-11eb-843f-5c6481c9a853.jpg)

Cheers for this! Works well so far.

**Comment by juavinas** [comment]
Hello,
 how you setup, what it is worked? Xiaomi_miot, I installed from HACS. What need to do next?

**Comment by bartohz** [comment]
> Hello,
> how you setup, what it is worked? Xiaomi_miot, I installed from HACS. What need to do next?

Once you install it via HACS, go into Configuration > Integrations > Add New Integration and search for Xiaomi Miot. From the dropdown menu the first option is to sign into your account and the second will be to manually add it. I added mine manually, you'll need to get your device IP and [token](https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-the-access-token). After that it'll show up as any other entity and you can control it from there. :)

**Comment by fredyerne** [comment]
Hello,
I just installed https://github.com/al-one/hass-xiaomi-miot via HACS, but after restart the there is no new "integration" for Xiaomi:

![image](https://user-images.githubusercontent.com/60570689/115999161-0bdf1900-a5eb-11eb-9ada-71213bf9191e.png)

![image](https://user-images.githubusercontent.com/60570689/115999179-1b5e6200-a5eb-11eb-87f7-785b249a5fd9.png)

any hint on what I do wrong?

Thanks!

**Comment by alesoft73** [comment]
@syssi You have predictions for this device integration ??
Many thanks ;)

**Comment by TristanHoogmoed** [comment]
We need an update..

**Comment by zawias** [comment]
> > Hello,
> > how you setup, what it is worked? Xiaomi_miot, I installed from HACS. What need to do next?
> 
> Once you install it via HACS, go into Configuration > Integrations > Add New Integration and search for Xiaomi Miot. From the dropdown menu the first option is to sign into your account and the second will be to manually add it. I added mine manually, you'll need to get your device IP and [token](https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-the-access-token). After that it'll show up as any other entity and you can control it from there. :)

Do you have manual rotation control in favorite mode?

**Comment by bartohz** [comment]
> > > Hello,
> > > how you setup, what it is worked? Xiaomi_miot, I installed from HACS. What need to do next?
> > 
> > 
> > Once you install it via HACS, go into Configuration > Integrations > Add New Integration and search for Xiaomi Miot. From the dropdown menu the first option is to sign into your account and the second will be to manually add it. I added mine manually, you'll need to get your device IP and [token](https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-the-access-token). After that it'll show up as any other entity and you can control it from there. :)
> 
> Do you have manual rotation control in favorite mode?

Not as far as I know and the manual mode doesn't have as many steps. I generally just set the favourite mode in the Xiaomi app and leave it at that. Then HA will just read that.

**Comment by forast3r** [comment]
You can set it from HA via 

> > > Hello,
> > > how you setup, what it is worked? Xiaomi_miot, I installed from HACS. What need to do next?
> > 
> > 
> > Once you install it via HACS, go into Configuration > Integrations > Add New Integration and search for Xiaomi Miot. From the dropdown menu the first option is to sign into your account and the second will be to manually add it. I added mine manually, you'll need to get your device IP and [token](https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-the-access-token). After that it'll show up as any other entity and you can control it from there. :)
> 
> Do you have manual rotation control in favorite mode?

Use the climate.set_property service in HA

**Comment by zawias** [comment]
> > > > Witam, 
> > > > jak konfigurujesz, na czym to działa? Xiaomi_miot, zainstalowałem z HACS. Co dalej?
> > > 
> > > 
> > > Po zainstalowaniu go przez HACS przejdź do Konfiguracja> Integracje> Dodaj nową integrację i wyszukaj Xiaomi Miot. Z menu rozwijanego pierwszą opcją jest zalogowanie się na swoje konto, a drugą będzie ręczne dodanie. Dodałem mój ręcznie, musisz uzyskać adres IP i [token](https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-the-access-token) swojego urządzenia . Następnie pojawi się jako każda inna jednostka i możesz nią sterować z tego miejsca. :)
> > 
> > 
> > Czy masz ręczną kontrolę obrotów w ulubionym trybie?
> 
> Użyj usługi Climate.set_property w HA

Mówisz o tym ? U mnie nie działa. 
![image](https://user-images.githubusercontent.com/49210393/118543559-afd46400-b754-11eb-98d0-979e6f6fd41a.png)

**Comment by forast3r** [comment]
> > > > > Witam,
> > > > > jak konfigurujesz, na czym to działa? Xiaomi_miot, zainstalowałem z HACS. Co dalej?
> > > > 
> > > > 
> > > > Po zainstalowaniu go przez HACS przejdź do Konfiguracja> Integracje> Dodaj nową integrację i wyszukaj Xiaomi Miot. Z menu rozwijanego pierwszą opcją jest zalogowanie się na swoje konto, a drugą będzie ręczne dodanie. Dodałem mój ręcznie, musisz uzyskać adres IP i [token](https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-the-access-token) swojego urządzenia . Następnie pojawi się jako każda inna jednostka i możesz nią sterować z tego miejsca. :)
> > > 
> > > 
> > > Czy masz ręczną kontrolę obrotów w ulubionym trybie?
> > 
> > 
> > Użyj usługi Climate.set_property w HA
> 
> Mówisz o tym ? U mnie nie działa.
> ![image](https://user-images.githubusercontent.com/49210393/118543559-afd46400-b754-11eb-98d0-979e6f6fd41a.png)

There was a typo in the service name, try developer tools, Service. The value in rpm:

```
service: xiaomi_miot.set_property
data:
  entity_id: climate.xiaomi_mc5_374e
  field: custom_service.favorite_speed
  value: 1500
```
We better ask for support in miiot threads...sorry for the noise

**Comment by nervous-inhuman** [comment]
I'm trying to get this Air Purifier to work nicely with [denysdovhan/purifier-card](https://github.com/denysdovhan/purifier-card)

![image](https://user-images.githubusercontent.com/8982584/120898080-b22a2f80-c629-11eb-9bfd-c100feb752d7.png)

Not everything is working (e.g. Power ON/OFF button; ON/OFF State; AQI on top of the purifier), as the card expects the Air Purifier to be a `fan` entity, with service calls for it hardcoded.

For anyone wanting to do the same, here's my card config: 

```
type: custom:purifier-card
entity: climate.3c_air_purifier
aqi:
  - entity: climate.3c_air_purifier
    attriubte: environment.pm2_5_density
stats:
  - attribute: filter.filter_life_level
    unit: '%'
    subtitle: Filter Remaining
  - attribute: custom_service.moto_speed_rpm
    unit: RPM
    subtitle: Motor Speed
  - attribute: environment.pm2_5_density
    unit: µg/m³
    subtitle: AQI
actions:
  - name: Silent
    icon: mdi:weather-night
    service: xiaomi_miot.set_property
    service_data:
      entity_id: climate.3c_air_purifier
      field: air_purifier.mode
      value: 1
  - name: 25%
    icon: mdi:circle-slice-2
    service: xiaomi_miot.set_property
    service_data:
      entity_id: climate.3c_air_purifier
      field: custom_service.favorite_speed
      value: 550
  - name: 50%
    icon: mdi:circle-slice-4
    service: xiaomi_miot.set_property
    service_data:
      entity_id: climate.3c_air_purifier
      field: custom_service.favorite_speed
      value: 1100
  - name: 75%
    icon: mdi:circle-slice-6
    service: xiaomi_miot.set_property
    service_data:
      entity_id: climate.3c_air_purifier
      field: custom_service.favorite_speed
      value: 1650
  - name: 100%
    icon: mdi:circle-slice-8
    service: xiaomi_miot.set_property
    service_data:
      entity_id: climate.3c_air_purifier
      field: custom_service.favorite_speed
      value: 2200
  - name: Auto
    icon: mdi:brightness-auto
    service: xiaomi_miot.set_property
    service_data:
      entity_id: climate.3c_air_purifier
      field: air_purifier.mode
      value: 0
show_name: true
show_state: true
show_toolbar: true
compact_view: false
```
