### ISSUE TITLE
deerma.humidifier.jsq doesn't work with integration

### ISSUE THREAD

**Issue by crusader2310** [syssi/xiaomi_airpurifier#131]
Hello to everyone! I bough a new humidifier Mi Smart Antibacterial Humidifier (or Mijia Intelligent Sterilization Humidifier (EU version?)), but it isn't working with the integration. I can add FAN, but it hasn't any attribute and have "Unknown" status. Can you help me with it, please? P.S. I am a nub in HA :) 
![image](https://user-images.githubusercontent.com/69865358/104729900-3434bd00-574a-11eb-9c43-8e49254be2bd.png)

**Comment by crusader2310** [comment]
![image](https://user-images.githubusercontent.com/69865358/104731585-fa18ea80-574c-11eb-9a1a-61cb06492224.png)

**Comment by photovirus** [comment]
I've got exactly the same problem. Logs follow:

```
2021-01-15 19:50:01 DEBUG (SyncWorker_3) [miio.miioprotocol] Discovered 0e9c26d0 with ts: 1970-01-20 18:42:11, token: b'ffffffffffffffffffffffffffffffff'
2021-01-15 19:50:01 DEBUG (SyncWorker_3) [miio.miioprotocol] 192.168.1.151:54321 >>: {'id': 1824, 'method': 'get_prop', 'params': ['OnOff_State']}
2021-01-15 19:50:06 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: timed out
2021-01-15 19:50:06 ERROR (MainThread) [custom_components.xiaomi_miio_airpurifier.fan] Got exception while fetching the state: No response from the device
2021-01-15 19:50:15 DEBUG (SyncWorker_2) [miio.miioprotocol] 192.168.1.151:54321 >>: {'id': 1825, 'method': 'get_prop', 'params': ['OnOff_State']}
2021-01-15 19:50:20 DEBUG (SyncWorker_2) [miio.miioprotocol] Retrying with incremented id, retries left: 3
2021-01-15 19:50:20 DEBUG (SyncWorker_2) [miio.protocol] Unable to decrypt, returning raw bytes: b''
2021-01-15 19:50:20 DEBUG (SyncWorker_2) [miio.miioprotocol] Got a response: Container:
data = Container:
data = b'' (total 0)
value = b'' (total 0)
offset1 = 32
offset2 = 32
length = 0
header = Container:
data = b'!1\x00 \x00\x00\x00\x00\x0e\x9c&\xd0\x00\x1a\x13\x96' (total 16)
value = Container:
length = 32
unknown = 0
device_id = unhexlify('0e9c26d0')
ts = 1970-01-20 18:42:30
offset1 = 0
offset2 = 16
length = 16
checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
2021-01-15 19:50:20 DEBUG (SyncWorker_2) [miio.miioprotocol] Discovered 0e9c26d0 with ts: 1970-01-20 18:42:30, token: b'ffffffffffffffffffffffffffffffff'
2021-01-15 19:50:20 DEBUG (SyncWorker_2) [miio.miioprotocol] 192.168.1.151:54321 >>: {'id': 1926, 'method': 'get_prop', 'params': ['OnOff_State']}
```

**Comment by syssi** [comment]
Are you sure your token and model is correct? Could you install `python-miio` to make some api calls via `miiocli`?

**Comment by photovirus** [comment]
> Are you sure your token and model is correct?

I'm sure I'm using `...jsq1`, per your table. However, I tried `...jsq` too, since `token_extractor.py` showed this model.

>  Could you install python-miio to make some api calls via miiocli?

Sure!

**Comment by syssi** [comment]
1. Please ask your device about the firmware and model name:

```
miiocli device --ip <ip> --token <token> info
```

**Comment by bens262** [comment]
Hello. I've got the same device and the same problem , when i choose deerma.humidifier.jsq in configuration.yaml to use platform: xiaomi_miio i get the error : 
`Invalid config for [fan.xiaomi_miio]: value must be one of ['zhimi.airfresh.va2', 'zhimi.airpurifier.m1', 'zhimi.airpurifier.m2', 'zhimi.airpurifier.ma1', 'zhimi.airpurifier.ma2', 'zhimi.airpurifier.ma4', 'zhimi.airpurifier.mb3', 'zhimi.airpurifier.mc1', 'zhimi.airpurifier.sa1', 'zhimi.airpurifier.sa2', 'zhimi.airpurifier.v1', 'zhimi.airpurifier.v2', 'zhimi.airpurifier.v3', 'zhimi.airpurifier.v5', 'zhimi.airpurifier.v6', 'zhimi.airpurifier.v7', 'zhimi.humidifier.ca1', 'zhimi.humidifier.ca4', 'zhimi.humidifier.cb1', 'zhimi.humidifier.v1'] for dictionary value @ data['model']. Got 'deerma.humidifier.jsq'. (See ?, line ?).`
miiocli device --ip <ip> --token <token> info answer is Model: deerma.humidifier.jsq
Hardware version: esp8266
Firmware version: 2.0.7

**Comment by bens262** [comment]
if i choose another model i've got 
`xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/fan.py", line 840, in async_update
    {
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/fan.py", line 841, in <dictcomp>
    key: self._extract_value_from_attribute(state, value)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/fan.py", line 698, in _extract_value_from_attribute
    value = getattr(state, attribute)
  File "/usr/local/lib/python3.8/site-packages/miio/airpurifier_miot.py", line 115, in mode
    return OperationMode(self.data["mode"])
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: None is not a valid OperationMode`

**Comment by photovirus** [comment]
> `miiocli device --ip <ip> --token <token> info`

Tried this. 

Initially got no response, but then tried another region, and everything got working. 

I remembered I attempted connecting the device with different regions in Mi Home. So I've got token from my second region, and voila, it connected instantly.

**Comment by bens262** [comment]
> > `miiocli device --ip <ip> --token <token> info`
> 
> Tried this.
> 
> Initially got no response, but then tried another region, and everything got working.
> 
> I remembered I attempted connecting the device with different regions in Mi Home. So I've got token from my second region, and voila, it connected instantly.

How have you connected to ha? do you choose MODEL: deerma.humidifier.jsq? and ha didn't get error Invalid config for [fan.xiaomi_miio]?

**Comment by photovirus** [comment]
> How have you connected to ha? do you choose MODEL: deerma.humidifier.jsq? and ha didn't get error Invalid config for [fan.xiaomi_miio]?

Please see [this comment,](https://github.com/syssi/xiaomi_airpurifier/issues/131#issuecomment-761055863) I've added my config section there.

**Comment by syssi** [comment]
@bens262 Please use this custom component (`xiaomi_miio_airpurifier`). The official version (`xiaomi_miio`) doesn't support the device yet.

**Comment by syssi** [comment]
@crusader2310 Could you make some `miiocli` calls, too?

**Comment by crusader2310** [comment]
> @crusader2310 Could you make some `miiocli` calls, too?

I would be happy, if you will tell me what to do :) I am a new guy in РФ topic, don't know many things

**Comment by crusader2310** [comment]
![image](https://user-images.githubusercontent.com/69865358/104818756-a4227080-583a-11eb-9a69-10f192921117.png)

This is the information from Gateway 3 integration

**Comment by syssi** [comment]
@crusader2310 In this case please use `model: deerma.humidifier.jsq`. Don't use `deerma.humidifier.jsq1`.

**Comment by crusader2310** [comment]
> @crusader2310 In this case please use `model: deerma.humidifier.jsq`. Don't use `deerma.humidifier.jsq1`.

I tried the .jsq model, but had the same problem

  - platform: xiaomi_miio_airpurifier
    name: Mi Smart Antibacterial Humidifier
    host: 192.168.0.4
    # mac: 64:90:C1:CE:79:4F
    token: 589f356ab084fa6077d7959590e94faa
    model: deerma.humidifier.jsq

![image](https://user-images.githubusercontent.com/69865358/104833551-96a4cf00-58aa-11eb-9817-3409ded0e27a.png)

**Comment by photovirus** [comment]
> > @crusader2310 Could you make some `miiocli` calls, too?
> 
> I would be happy, if you will tell me what to do :) I am a new guy in HA topic, don't know many things

You should have python installed on your hass system, so fire up your terminal and install `python-miio`:
```
$ pip install python-miio
```

Then you'll be able to interface with your device directly:
```
$ miiocli device --ip <ip> --token <token> info
```

**Comment by crusader2310** [comment]
> > > @crusader2310 Could you make some `miiocli` calls, too?
> > 
> > 
> > I would be happy, if you will tell me what to do :) I am a new guy in HA topic, don't know many things
> 
> You should have python installed on your hass system, so fire up your terminal and install `python-miio`:
> 
> ```
> $ pip install python-miio
> ```
> 
> Then you'll be able to interface with your device directly:
> 
> ```
> $ miiocli device --ip <ip> --token <token> info
> ```

Can you tell me, please, in which region did you add device to Mi Home? I tried Russia, Germany and UK - and still nothing happened.

**Comment by syssi** [comment]
Please be aware: Each time you reset the device / change the region the devices generates a new token. The custom component should work on any region if the token is correct. You should select a region near to your location if possible.

**Comment by photovirus** [comment]
> Can you tell me, please, in which region did you add device to Mi Home? I tried Russia, Germany and UK - and still nothing happened.

Russia worked. 

First, I tried to connect my humidifier to the Chinese region, then to the Russian. I suppose only the latest link works (but don't have reliable proof, of course).

**Comment by crusader2310** [comment]
> > Can you tell me, please, in which region did you add device to Mi Home? I tried Russia, Germany and UK - and still nothing happened.
> 
> Russia worked.
> 
> First, I tried to connect my humidifier to the Chinese region, then to the Russian. I suppose only the latest link works (but don't have reliable proof, of course).

I started from Russia (Chineese doesn't accept my device at all), then Europe - and every time it shows me that information about my device in HA isn't accessible. And I don't have any attributes except fan speed (which doesn't work too)

**Comment by crusader2310** [comment]
> Please be aware: Each time you reset the device / change the region the devices generates a new token. The custom component should work on any region if the token is correct. You should select a region near to your location if possible.

Also I have this type of error, when I choose any region:

![image](https://user-images.githubusercontent.com/69865358/105155445-a840dd80-5b1b-11eb-84eb-a23d55495709.png)

**Comment by syssi** [comment]
@crusader2310 This is fine. The custom component doesn't provide a "unique id" if no model is set at the configuratoin. You are able to rename the entity if an unique id is available. There are no more drawbacks. Please check your `home-assistant.log` for errors.

**Comment by Kirmas** [comment]
> @crusader2310 This is fine. The custom component doesn't provide a "unique id" if no model is set at the configuratoin. You are able to rename the entity if an unique id is available. There are no more drawbacks. Please check your `home-assistant.log` for errors.

unique id is require if i want add entity without device to area, isnt it? (from ha v 2020.12.1)

**Comment by syssi** [comment]
@Kirmas If you provide a `model` at the configuration an unique id is generated/provided. If your device doesn't work and you don't know the exact model don`t use the model option to autodetect the device. The option can be added later.

**Comment by KMDobrev** [comment]
Hello,

I have the same device. I can turn the device on and off.
My problem is the buzzer and led buttons are not working.

**Comment by syssi** [comment]
@KMDobrev Could you create a new issue and provide some logs?

https://github.com/syssi/xiaomi_airpurifier#debugging

**Comment by KMDobrev** [comment]
> @KMDobrev Could you create a new issue and provide some logs?
> 
> https://github.com/syssi/xiaomi_airpurifier#debugging


Do you think this code is correct?

`fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Humidifer
    host: 192.168.xxx.xxx
    token: xxxxx
    model: deerma.humidifier.jsq
    
sensor:
  - platform: template
    sensors:
      airhumidifier_temperature:
        friendly_name: Air Humidifier Temperature
        value_template: '{{ states.fan.xiaomi_humidifer.attributes.temperature }}'
        unit_of_measurement: '°C'
      airhumidifier_humidity:
        friendly_name: Air Humidifier Humidity
        value_template: '{{ states.fan.xiaomi_humidifer.attributes.humidity }}'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
switch:
  - platform: template
    switches:
      xiaomi_airpurifier_buzzer:
        friendly_name: "Buzzer"
        value_template: "{{ is_state_attr('fan.xiaomi_air_purifier', 'buzzer', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_on
          data:
            entity_id: fan.xiaomi_air_purifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_off
          data:
            entity_id: fan.xiaomi_air_purifier
        icon_template: "mdi:volume-off"

      xiaomi_airpurifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.xiaomi_air_purifier', 'led', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_led_on
          data:
            entity_id: fan.xiaomi_air_purifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_led_off
          data:
            entity_id: fan.xiaomi_air_purifier
        icon_template: "mdi:lightbulb-outline"
logger:
  default: warn
  logs:
    custom_components.xiaomi_miio_airpurifier: debug
    miio: debug`

**Comment by syssi** [comment]
Your configuration isn't correct. Take a look at http://hass-ip:hass-port/developer-tools/state and provide a screenshot of your fan entity. I assume the entity id is `fan.xiaomi_humidifier`. Search for call occurrence of `fan.` at your configuration. You are accessing the entity `fan.xiaomi_air_purifier` here but you want to access `fan.xiaomi_humidifier`.

**Comment by KMDobrev** [comment]
> Your configuration isn't correct. Take a look at http://hass-ip:hass-port/developer-tools/state and provide a screenshot of your fan entity. I assume the entity id is `fan.xiaomi_humidifier`. Search for call occurrence of `fan.` at your configuration. You are accessing the entity `fan.xiaomi_air_purifier` here but you want to access `fan.xiaomi_humidifier`.

Thank you so much. It is currently working.

```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Humidifer
    host: 192.168.178.34
    token: 7aa102a5f512092e268df58f35d14a00
    model: deerma.humidifier.jsq
    
sensor:
  - platform: template
    sensors:
      airhumidifier_temperature:
        friendly_name: Air Humidifier Temperature
        value_template: '{{ states.fan.xiaomi_humidifer.attributes.temperature }}'
        unit_of_measurement: '°C'
      airhumidifier_humidity:
        friendly_name: Air Humidifier Humidity
        value_template: '{{ states.fan.xiaomi_humidifer.attributes.humidity }}'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
switch:
  - platform: template
    switches:
      xiaomi_airpurifier_buzzer:
        friendly_name: "Buzzer"
        value_template: "{{ is_state_attr('fan.xiaomi_humidifer', 'buzzer', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_on
          data:
            entity_id: fan.xiaomi_humidifer
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_off
          data:
            entity_id: fan.xiaomi_humidifer
        icon_template: "mdi:volume-off"

      xiaomi_airpurifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.xiaomi_humidifer', 'led', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_led_on
          data:
            entity_id: fan.xiaomi_humidifer
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_led_off
          data:
            entity_id: fan.xiaomi_humidifer
        icon_template: "mdi:lightbulb-outline"
```
