### ISSUE TITLE
Suggestion of dmaker.airfresh.t2017's Configuration

### ISSUE THREAD

**Issue by DeakeyTan** [syssi/xiaomi_airpurifier#132]
Hello, I tried the configuration of t2017, and I found that the 'current speed' is equal to the speed of the favorite mode, but the device will not always run in the favorite mode.
I suggest using 'current speed' to display the current running speed, and 'favorite speed' to display the setting value of favorite speed, so the code will change:

Old:
```
       xiaomi_fresh_air_ventilator_current_speed:
         friendly_name: Current speed
         value_template:'{{ states.fan.xiaomi_fresh_air_ventilator.attributes.favorite_speed }}'
         icon_template: mdi:speedometer
```

New:
```
       xiaomi_fresh_air_ventilator_current_speed:
         friendly_name: Current speed
         value_template:'{{ states.fan.xiaomi_fresh_air_ventilator.attributes.control_speed }}'
         icon_template: mdi:speedometer
       xiaomi_fresh_air_ventilator_favorite_speed:
         friendly_name: Favorite speed
         value_template:'{{ states.fan.xiaomi_fresh_air_ventilator.attributes.favorite_speed }}'
```

<img width="477" alt="Snipaste_2021-01-17_01-37-01" src="https://user-images.githubusercontent.com/40329013/104818754-879b2e00-5864-11eb-93d6-dd54447e6f46.png">

Thank you for your work and dedication.
