### ISSUE TITLE
Add dmaker.fan.p15 support

### ISSUE THREAD

**Issue by sjdvda** [syssi/xiaomi_airpurifier#141]
My understanding is that dmaker.fan.p15 is the European version of dmaker.fan.p11, which is supported.

Details: 
Name: Mi Smart Standing Fan Pro EU
Model: dmaker.fan.p15
Model no: ZLBPSP01XY
Specs: 2800 mAh, 24W, <=58dB

**Comment by eliorerz** [comment]
I need that too. Any idea what is the status?

**Comment by kaazvaag** [comment]
I also have a dmaker.fan.p15. Could you support this device?

**Comment by Piramidowy** [comment]
+1

**Comment by Intelligenzbestie** [comment]
It's working for me (with the aforementioned restrictions using this in configuration.yaml:
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Smart Fan Pro
    host: IP address of the fan
    token: xxx your token xxx
    model: dmaker.fan.p11

I retrieved the token using this: https://github.com/Maxmudjon/Get_MiHome_devices_token/releases

**Comment by Piramidowy** [comment]
Weird, I'm still getting info that fan is unable to be discovered:
`INFO (MainThread) [custom_components.xiaomi_miio_airpurifier.fan] Got exception while fetching the state: Unable to discover the device 192.168.x.x , _retry=1`

My config:
```
# Xiaomi Smart Fan Pro #
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Smart Fan Pro
    host: 192.168.x.xxx
    token: xxxxxxxxxxxxxxxxx
    model: dmaker.fan.p11
```
