### ISSUE TITLE
The light switch doesn't work \ Не работает выключатель света

### ISSUE THREAD

**Issue by DivanX10** [syssi/xiaomi_airpurifier#177]
After the update, my light switch stopped working. I can only turn on the light, and I can't turn it off. If you turn off and turn on the light from the MiHome app, the switch changes the status.

После обновления у меня перестал работать выключатель света. Я могу только включить свет, а выключить не могу. Если выключить и включить свет из приложения MIHome, то выключатель меняет статус.

Xiaomi Mi Air Purifier & Xiaomi Mi Air Humidifier ver: 0.6.8
Model: deerma.humidifier.jsq1
```
switch:
  - platform: template
    switches:
      xiaomi_airpurifier_buzzer:
        friendly_name: "Buzzer"
        value_template: "{{ is_state_attr('fan.smart_sterilization_humidifier_s', 'buzzer', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_on
          data:
            entity_id: fan.smart_sterilization_humidifier_s
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_off
          data:
            entity_id: fan.smart_sterilization_humidifier_s
        icon_template: "mdi:volume-off"

      xiaomi_airpurifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.smart_sterilization_humidifier_s', 'led', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_led_on
          data:
            entity_id: fan.smart_sterilization_humidifier_s
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_led_off
          data:
            entity_id: fan.smart_sterilization_humidifier_s
        icon_template: "mdi:lightbulb-outline"

```
