### ISSUE TITLE
2021.5 - problem with sensor

### ISSUE THREAD

**Issue by Omirax** [syssi/xiaomi_airpurifier#186]
Hello!

After update from 2021.3 to 2021.5 have some problems with 2 purifiers.

I'm use this for sensor:
```
sensor:
  - platform: template
    sensors:
      airpurifier_aqi:
        friendly_name: Air Purifier Air Quality Index
        value_template: '{{ states.fan.xiaomi_2h.attributes.aqi }}'
        icon_template: mdi:weather-windy
```
With this automation:
```
  automation:
        - alias: xiaomi_2h turn off 
          id: xiaomi_2h_auto_off
          trigger:
            - platform: numeric_state
              entity_id: sensor. airpurifier_aqi
              value_template: "{{ states('sensor. airpurifier_aqi') | int}}"
              below: 3
              for:
                minutes: 5
          condition:
            - condition: state
              entity_id: 'fan.xiaomi_2h'
              state: 'on'
          action:
            service: fan.turn_off
            entity_id: fan.xiaomi_2h
```
After update the trigger never fires!
Whats happened?

**Comment by Omirax** [comment]
This custom component version

**Comment by syssi** [comment]
If you remove these lines:

```
for:
  minutes: 5
```

Does the automation work?

**Comment by Omirax** [comment]
No.
Don't work

**Comment by syssi** [comment]
If you evaluate the template 

```
{{ states('sensor. airpurifier_aqi') | int}}
```

via `/developer-tools/template` does it return a proper value?

**Comment by Omirax** [comment]
Yes. All correct. 
Result: number
9

**Comment by syssi** [comment]
Could you remove the duration to make the testing easier. A single sensor update would trigger the sensor in this case. Please also remove the state condition just for testing. Is your automation enabled? Please provide a screenshot of the `dev-state` page showing the automation.* entity. If you trigger the automation manually does the air purifier turn off?

**Comment by Omirax** [comment]
> If you trigger the automation manually does the air purifier turn off?
Yes.
> Is your automation enabled?
Yes.

I have been using Nome Assist for several years 

Below are two automations.
The first is your template sensor - temperature
The second is the xiaomi temperature sensor 

First - don't work, second - work perfect

```
- alias: 'automations test'
  id: '1578857709245'
  trigger:
        - below: 100
         platform: numeric_state
         entity_id:  sensor. airpurifier_temp
         value_template: ""{{ states('sensor. airpurifier_temp') | int}}"
         for: '00:01:00'
  action:
    - service: notify.persistent_notification
      data:
        message: "airpurifier_temperature trigger"
  mode: restart


- alias: 'automations 2 test'
  id: '1578857709s245'
  trigger:
  - below: '100'
    entity_id: sensor.env_office_temperature
    for: '00:01:30'
    platform: numeric_state
  action:
    - service: notify.persistent_notification
      data:
        message: "env_office_temperature trigger"
  mode: restart
```

**Comment by syssi** [comment]
Why do you use the template_value construct? It should work without.

**Comment by Omirax** [comment]
Hmmm...

This work:
```- alias: 'automations 2 test'
  id: '1578857709ss245'
  trigger:
  - platform: time_pattern
    minutes: '/1'
  condition:
  - condition: numeric_state   
    below: '100'
    entity_id: sensor.airpurifier_temp
  action:
    - service: notify.persistent_notification
      data:
        message: "airpurifier_temp /1 trigger"
  mode: restart
```
  
  This - don't work
  
  ```
- alias: 'automations test'
  id: '1578857709245'
  trigger:
    - below: 100
      platform: numeric_state
      entity_id:  sensor.airpurifier_temp
#      value_template: "{{ states('sensor.airpurifier_temp') | float}}"
#      for: '00:01:00'
  action:
    - service: notify.persistent_notification
      data:
        message: "airpurifier_temperature trigger"
  mode: restart
```
