### ISSUE TITLE
Retrieving Temperature and Humidity

### ISSUE THREAD

**Issue by tldrake89** [syssi/xiaomi_airpurifier#21]
Hello,

First of all thank you for this component!
I would like to ask you if there is any way to retrieve the temperature as well the humidity from Xiomi AirPurifier?
Regards

**Comment by syssi** [comment]
Humidity and temperature is already provided as attribute. What do you need? Do you like the values a sensor data?

**Comment by syssi** [comment]
You could use a sensor template which provides the attribute values as sensor values:

```
sensor:
  - platform: template
    sensors:
      airpurifier_aqi:
        friendly_name: Air Purifier Air Quality Index
        value_template: '{{ states.fan.xiaomi_air_purifier.attributes.aqi }}'
      airpurifier_temperature:
        friendly_name: Air Purifier Air Quality Index
        value_template: '{{ states.fan.xiaomi_air_purifier.attributes.temperature }}'
      airpurifier_humidity:
        friendly_name: Air Purifier Air Quality Index
        value_template: '{{ states.fan.xiaomi_air_purifier.attributes.humidity }}'
```
