### ISSUE TITLE
Setup should be simplified. 

### ISSUE THREAD

**Issue by precz** [syssi/xiaomi_airpurifier#212]
I do no understand why I need to retrieve tokens when native integration allows me to just log in into xiaomi cloud. Couldn't this be simplified? If this could not be achieved, better step by step instruction should be added.
After installing from HACS shouldn't it be available just as native one? Do I have to put something in `configuration.yaml`? What exactly? In what format? 
I'm not hassio expert, I just want my airpurifier added to my hassio setup. 
Please, could you lower the bar for new hassio users?

**Comment by syssi** [comment]
> I do no understand why I need to retrieve tokens when native integration allows me to just log in into xiaomi cloud. Couldn't this be simplified? If this could not be achieved, better step by step instruction should be added.

If the official component supports your device you should use it! If the device isn't supported officially you should try to use this custom component.

> After installing from HACS shouldn't it be available just as native one?

After installing from HACS you have to add something like this to your `configuration.yaml`:

```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Purifier 2
    host: 192.168.130.71
    token: b7c4a758c251955d2c24b1d9e41ce47d
```

The token is important.

> Do I have to put something in configuration.yaml? What exactly? In what format?

Take a look above.

> I'm not hassio expert, I just want my airpurifier added to my hassio setup.

Which device / model do you own?

> Please, could you lower the bar for new hassio users?

Feel free to add some instructions / contribute! I will try to help to get your device up and running.

**Comment by precz** [comment]
Thanks for your answer.

> Feel free to add some instructions / contribute! I will try to help to get your device up and running.

I'll be happy to do that. 

> Which device / model do you own?

Mi Smart Antibacterial Humidifier `deerma.humidifier.jsq5`

> The token is important.

I managed to get token, found this [instruction](https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md)

> After installing from HACS you have to add something like this to your `configuration.yaml`:

I have added: 
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Mi Smart Antibacterial Humidifier
    host: 192.168.1.40
    token: <my_token>
```
Now I got an error: 
```
Logger: custom_components.xiaomi_miio_airpurifier.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:1687 
Integration: xiaomi_miio_airpurifier (documentation, issues) 
First occurred: 10:02:14 (18 occurrences) 
Last logged: 10:10:49

Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}
```
Thanks again for your help!
