### ISSUE TITLE
Fix/improve deerma.humidifier.jsq5 support

### ISSUE THREAD

**Issue by DmitryTankovich** [syssi/xiaomi_airpurifier#213]
Hello, I always have this error
`{'code': -9999, 'message': 'user ack timeout'}`

config:
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: 192.168.31.76
    token: **********
    model: deerma.humidifier.jsq5
```

**Comment by re-id** [comment]
I have the same problem

**Comment by dpozimski** [comment]
I double checked it, unfortunately it seems that it doesn’t work. 
Device is not sending a response on initialization step.

**Comment by devpitx** [comment]
I have the same issue

> Logger: custom_components.xiaomi_miio_airpurifier.fan
> Source: custom_components/xiaomi_miio_airpurifier/fan.py:1687
> Integration: xiaomi_miio_airpurifier (documentation, issues)
> First occurred: 14:43:19 (14 occurrences)
> Last logged: 14:49:58

Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}

```
$ miiocli device --ip 192.168.0.13 --token be4b0aa68422a2986a32708b459795a1 info
Model: deerma.humidifier.jsq5
Hardware version: esp8266
Firmware version: 2.0.7
```

```
fan:
    platform: xiaomi_miio_airpurifier
    host: 192.168.0.13
    model: deerma.humidifier.jsq5
    token: *******************
    name: xiaomi_humidifier
```
