### ISSUE TITLE
Got exception while fetching the state: Unable to discover the device

### ISSUE THREAD

**Issue by JohnnyM84** [syssi/xiaomi_airpurifier#232]
Iám trying to add an Xiaomi mi antibacterial humidifier, it should be supported it's an deerma.humidifier.jsq5.
This is my config:
```yml
fan:
  - platform: xiaomi_miio_airpurifier
    name: Humidifier Office
    host: ip_address
    token: token
    model: deerma.humidifier.jsq5
```
But in de logging i am getting this error:
Got exception while fetching the state: Unable to discover the device ip_address

With extra debug logging on i get no extra messages.
What can be the problem?
