### ISSUE TITLE
Unsupported device found: zhimi.airfresh.va2 （智米新风）

### ISSUE THREAD

**Issue by Yonsm** [syssi/xiaomi_airpurifier#25]
Please help support the SmartMi Air Fresh System. The device model ID is `zhimi.airfresh.va2`

With the following configuration, it can almost work well (Turn On/Off, aqi, humidity, etc.) :

```yaml
  - platform: xiaomi_miio
    name: Fresher
    host: 192.168.1.x
    model: zhimi.airpurifier.m1
    token: ****************
```

BTW, Could you please tell me how to sniffer/analyze miio traffic payload with the new device? I found [https://github.com/OpenMiHome/mihome-binary-protocol](https://github.com/OpenMiHome/mihome-binary-protocol), but it can't analysis the traffic between MiHome app and Xiaomi Cloud, and I couldn't find how to enforce/repeat the device and MiHome app to communication via local protocol. Your help will be highly appreciated:)
