### ISSUE TITLE
No module named 'miio.fan'

### ISSUE THREAD

**Issue by sshostka** [syssi/xiaomi_airpurifier#252]
I'm getting such error when checking my configuration or trying to restart HA:
`Platform error fan.xiaomi_miio_airpurifier - No module named 'miio.fan'`

my config:
```
  fan:
    - platform: xiaomi_miio_airpurifier
      host: 192.168.1.104
      model: zhimi.humidifier.ca1
      name: "Humidifier #1"
      token: !secret xiaomi_humidifier1_token
    - platform: xiaomi_miio_airpurifier
      host: 192.168.1.203
      model: zhimi.humidifier.ca1
      name: "Humidifier #2"
      token: !secret xiaomi_humidifier2_token
```
HA Version `core-2021.11.5`
Custom component version = `"0.6.17"` (depends on `python-miio>=0.5.9.2`)
also default miio component installed (which I believe depends on `python-miio==0.5.10`)

I do think that this start appearing after last HA restart but I suppose nothing related was changed. I even tried to revert my changes from last restart.

@syssi do you have any idea why this happened?
