### ISSUE TITLE
Support for deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by Proche72** [syssi/xiaomi_airpurifier#271]
This is smart antibacterial humidifier, bought in Czech Republic.

**Comment by HenrikHills** [comment]
I got the same "error", unless they have changed something with the humidifier model, i should work if you add it in YAML mode

**Comment by Proche72** [comment]
Do you have some link for the YAML mode? I am not able to find it.

**Comment by syssi** [comment]
1. Step: https://github.com/syssi/xiaomi_airpurifier#install
2. Step: https://github.com/syssi/xiaomi_airpurifier#setup

```
# configuration.yaml

fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: <IP_ADDRESS>
    token: <TOKEN>
    model: deerma.humidifier.jsq5
```

**Comment by engusz** [comment]
Hi @syssi 
It doesn't work under 2022.4.0.1 either.
Same mistake as I wrote above.

**Comment by syssi** [comment]
Could you enable the debug output of the custom component and the underlying library by:

```
logger:
  default: warn
  logs:
    custom_components.xiaomi_miio_airpurifier: debug
    miio: debug
```

And provide some logs?
