### ISSUE TITLE
zhimi.airpurifier.za1 unable to switch on/off

### ISSUE THREAD

**Issue by pniewiadowski** [syssi/xiaomi_airpurifier#273]
I have two SmartMI air purifier and would like to integrate it to Home Assistant.
Here is the part of the `configuration.yaml`

```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Air Purifier Office
    host: ip_address
    token: xxx
    model: zhimi.airpurifier.za1
  - platform: xiaomi_miio_airpurifier
    name: Air Purifier Living Room
    host: ip_address
    token: xxx
    model: zhimi.airpurifier.za1  
```

Entities are available in Home Assistant, but I can't control it. Although unit is on, HA shows it as off.
Is it known issue, or I did something wrong?

![image](https://user-images.githubusercontent.com/28837813/160010217-a3b76985-5546-4e1f-a17b-af0f9ee6f02e.png)
