### ISSUE TITLE
Unsupported device found

### ISSUE THREAD

**Issue by actstorms** [syssi/xiaomi_airpurifier#291]
```Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:154
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 01:24:12 (1 occurrences)
Last logged: 01:24:12

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5```

**Comment by epolinom** [comment]
same problem

**Comment by than0s** [comment]
+1

**Comment by maikvitesse** [comment]
Same problem 😔
Model number: ZNJSQ01DEM

**Comment by rostislavYurievich** [comment]
+1

**Comment by PeRRo-RoJo** [comment]
Same issue

**Comment by Staggeble** [comment]
+1

**Comment by tanasecosminromeo** [comment]
+1

**Comment by pavvel11** [comment]
+1

**Comment by olivapetr** [comment]
+1

**Comment by 1uqtpfcn6hh8** [comment]
Same issue

**Comment by PeRRo-RoJo** [comment]
De este modo he conseguido hacerlo funcionar. Pegar el código en los siguientes archivos:
I have managed to get it to work. Paste the code in the following files:

/hass-config/automations.yaml
```
#Gestión de humedad continua
  - alias: Select target humidity by slider
    trigger:
      platform: state
      entity_id: input_number.airhumidifier_target_humidity
    action:
      - service: xiaomi_miio_airpurifier.fan_set_target_humidity
        data_template:
          entity_id: fan.xiaomi_air_humidifier
          humidity: '{{ states.input_number.airhumidifier_target_humidity.state|int }}'

  - alias: Monitor target humidity and update slider
    trigger:
      platform: state
      entity_id: sensor.airhumidifier_target_humidity
    action:
      service: input_number.set_value
      entity_id: input_number.airhumidifier_target_humidity
      data_template:
        value: '{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}'
        
#Gestión de los modos de humidificación
  - alias: Select operation mode by input select
    trigger:
      entity_id: input_select.airhumidifier_mode
      platform: state
    action:
      service: fan.set_preset_mode
      data_template:
        entity_id: fan.xiaomi_air_humidifier
        preset_mode: '{{ states.input_select.airhumidifier_mode.state }}'

  - alias: Monitor operation mode and update input select
    trigger:
      platform: state
      entity_id: fan.xiaomi_air_humidifier
    action:
      service: input_select.select_option
      entity_id: input_select.airhumidifier_mode
      data_template:
        option: '{{ states.fan.xiaomi_air_humidifier.attributes.preset_mode }}'
```

/hass-config/configuration.yaml
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: iphumidifier
    token: tokenhumidifier
    model: deerma.humidifier.jsq5

sensor:
  - platform: template
    sensors:
      airhumidifier_temperature:
        friendly_name: Temperatura ambiente
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.temperature }}'
        unit_of_measurement: '°C'
      airhumidifier_humidity:
        friendly_name: Humedad ambiente
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.humidity }}'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
      airhumidifier_target_humidity:
        friendly_name: Humedad programada
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
      airhumidifier_no_water:
        friendly_name: Deposito vacio
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.no_water }}'
        icon_template: mdi:cup-outline
      airhumidifier_water_tank_detached:
        friendly_name: Deposito no detectado
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.water_tank_detached }}'
        icon_template: mdi:cup-off-outline
        
switch:
  - platform: template
    switches:
      xiaomi_airhumidifier_buzzer:
        friendly_name: "Buzzer"
        value_template: "{{ is_state_attr('fan.xiaomi_air_humidifier', 'buzzer', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_on
          data:
            entity_id: fan.xiaomi_air_humidifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_off
          data:
            entity_id: fan.xiaomi_air_humidifier
        icon_template: "mdi:volume-off"

      xiaomi_airhumidifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.xiaomi_air_humidifier', 'led', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_led_on
          data:
            entity_id: fan.xiaomi_air_humidifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_led_off
          data:
            entity_id: fan.xiaomi_air_humidifier
        icon_template: "mdi:lightbulb-outline"
        
input_select:
  airhumidifier_mode:
    name: Modo humidificación
    options:
     - Low
     - Mid
     - High
     - Auto
    icon: "mdi:animation-outline"

input_number:
  airhumidifier_target_humidity:
    name: Humedad deseada
    min: 1
    max: 99
    step: 1
```

Lovelace:
```
type: entities
entities:
  - entity: sensor.airhumidifier_temperature
  - entity: sensor.airhumidifier_humidity
  - entity: sensor.airhumidifier_target_humidity
  - entity: sensor.airhumidifier_no_water
  - entity: sensor.airhumidifier_water_tank_detached
  - entity: fan.xiaomi_air_humidifier
  - entity: input_select.airhumidifier_mode
  - entity: input_number.airhumidifier_target_humidity
  - entity: switch.xiaomi_airhumidifier_buzzer
  - entity: switch.xiaomi_airhumidifier_led
state_color: true
title: Xiaomi Air Humidifier
show_header_toggle: false

```
![image](https://user-images.githubusercontent.com/100376178/184149146-7379955c-5c9d-47df-996d-44cba66cd5e6.png)
