### ISSUE TITLE
Unsupported device found

### ISSUE THREAD

**Issue by whiteOS** [syssi/xiaomi_airpurifier#306]
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2g

**Comment by Pakato** [comment]
Same here

**Comment by EvanLjp** [comment]
same problem

**Comment by ABnSultan** [comment]
same

**Comment by ABnSultan** [comment]
found workaround, try to use either of these:
deerma.humidifier.jsq3
deerma.humidifier.jsq5
deerma.humidifier.jsqs

and it will work for you to control and read the data.

**Comment by GrKoR** [comment]
the same request

**Comment by maxifly** [comment]
Same request

**Comment by GrKoR** [comment]
Hi, @Schnabulation !

I wrote a config to solve this problem for myself. Feel free to use it if you need it.

Known bugs:
* `Medium` operation mode doesn't work. `Low`, `High` and `Auto` works great.
* When water tank becomes empty, notifier sends a message. However, later the water seems to flow down the device's walls and an erroneous notification arrives, that the water tank have been refilled.
I didn't immediately notice these bugs and still haven't found the time to deal with them... =)

```yaml
fan humidifier:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: <<IP_HERE>>
    token: <<TOKEN_HERE>>
    model: deerma.humidifier.jsq2w

switch:
  - platform: template
    switches:
      humidifier:
        friendly_name: Humidifier
        unique_id: <<RANDOM_UUID>>
        value_template: "{{ is_state('fan.xiaomi_air_humidifier', 'on') }}"
        turn_on:
          action: fan.turn_on
          target:
            entity_id: fan.xiaomi_air_humidifier
        turn_off:
          action: fan.turn_off
          target:
            entity_id: fan.xiaomi_air_humidifier
        icon_template: mdi:air-humidifier

      humidifier_buzzer:
        friendly_name: Buzzer
        unique_id: <<RANDOM_UUID>>
        value_template: "{{ is_state_attr('fan.xiaomi_air_humidifier', 'buzzer', True) }}"
        turn_on:
          action: xiaomi_miio_airpurifier.fan_set_buzzer_on
          data:
            entity_id: fan.xiaomi_air_humidifier
        turn_off:
          action: xiaomi_miio_airpurifier.fan_set_buzzer_off
          data:
            entity_id: fan.xiaomi_air_humidifier
        icon_template: mdi:volume-high

      humidifier_led:
        friendly_name: LED
        unique_id: <<RANDOM_UUID>>
        value_template: "{{ is_state_attr('fan.xiaomi_air_humidifier', 'led', True) }}"
        turn_on:
          action: xiaomi_miio_airpurifier.fan_set_led_on
          data:
            entity_id: fan.xiaomi_air_humidifier
        turn_off:
          action: xiaomi_miio_airpurifier.fan_set_led_off
          data:
            entity_id: fan.xiaomi_air_humidifier
        icon_template: mdi:led-outline

sensor:
  - platform: template
    sensors:
      humidifier_humidity:
        friendly_name: Humidity
        unique_id: <<RANDOM_UUID>>
        value_template: "{{ state_attr('fan.xiaomi_air_humidifier', 'humidity') }}"
        unit_of_measurement: "%"
        icon_template: mdi:water-percent

      humidifier_temperature:
        friendly_name: Temperature
        unique_id: <<RANDOM_UUID>>
        value_template: "{{ state_attr('fan.xiaomi_air_humidifier', 'temperature') }}"
        unit_of_measurement: "°C"
        icon_template: mdi:thermometer

binary_sensor:
  - platform: template
    sensors:
      humidifier_water_tank_detached:
        friendly_name: Water Tank Detached
        unique_id: <<RANDOM_UUID>>
        value_template: "{{ state_attr('fan.xiaomi_air_humidifier', 'no_water') }}" # attributes no_water and water_tank_detached are mixed up in the device!
        icon_template: >-
          {% if state_attr('fan.xiaomi_air_humidifier', 'no_water') %}
            mdi:cup-outline
          {% else %}
            mdi:cup-water
          {% endif %}
        device_class: problem

      humidifier_no_water:
        friendly_name: Water
        unique_id: <<RANDOM_UUID>>
        value_template: "{{ state_attr('fan.xiaomi_air_humidifier', 'water_tank_detached') }}" # attributes no_water and water_tank_detached are mixed up in the device!
        icon_template: >-
          {% if state_attr('fan.xiaomi_air_humidifier', 'water_tank_detached') %}
            mdi:water-off
          {% else %}
            mdi:water
          {% endif %}
        device_class: problem

input_select:
  humidifier_mode:
    name: Operation mode
    options:
      - Auto
      - Low
      - Medium
      - High

  humidifier_target_humidity:
    name: Target humidity
    options:
      - "30"
      - "40"
      - "50"
      - "60"
      - "70"
      - "80"

automation:
  - alias: Humidifier - select operation mode by input select
    trigger:
      entity_id: input_select.humidifier_mode
      trigger: state
    actions:
      action: fan.set_preset_mode
      data_template:
        entity_id: fan.xiaomi_air_humidifier
        preset_mode: "{{ states('input_select.humidifier_mode') }}"

  - alias: Humidifier - monitor operation mode and update input select
    triggers:
      trigger: template
      value_template: "{{ state_attr('fan.xiaomi_air_humidifier', 'preset_mode') }}"
    actions:
      action: input_select.select_option
      entity_id: input_select.humidifier_mode
      data_template:
        option: >
          {{ state_attr('fan.xiaomi_air_humidifier', 'preset_mode') }}

  - alias: Humidifier - select target humidity by input select
    triggers:
      trigger: state
      entity_id: input_select.humidifier_target_humidity
    actions:
      action: xiaomi_miio_airpurifier.fan_set_target_humidity
      data_template:
        entity_id: fan.xiaomi_air_humidifier
        humidity: >
          {{ states('input_select.humidifier_target_humidity') }}

  - alias: Humidifier - monitor target humidity and update input select
    triggers:
      trigger: template
      value_template: "{{ state_attr('fan.xiaomi_air_humidifier', 'target_humidity') }}"
    actions:
      action: input_select.select_option
      entity_id: input_select.humidifier_target_humidity
      data_template:
        option: >
          {{ state_attr('fan.xiaomi_air_humidifier', 'target_humidity') }}

  - alias: Humidifier - water is out notifier
    triggers:
      trigger: template
      value_template: "{{ state_attr('fan.xiaomi_air_humidifier', 'water_tank_detached') }}"
    actions:
      - action: <<NOTIFIER_ID_HERE>>
        data:
          message: "Humidifier: Water tank is empty"

  - alias: Humidifier - water refilled
    triggers:
      trigger: template
      value_template: "{{ not state_attr('fan.xiaomi_air_humidifier', 'water_tank_detached') }}"
    actions:
      - action: <<NOTIFIER_ID_HERE>>
        data:
          message: "Humidifier: Water have been refilled"
```
