### ISSUE TITLE
Change the frequency of sensors/atributes updatess

### ISSUE THREAD

**Issue by MasterSmurf** [syssi/xiaomi_airpurifier#340]
I'm very happy with the integration and got my  Xiaomi Air Humidifier up and running.
But I couldn't figure one thing; how can you change the frequency of sensor updates? For example the is updated every 90 secs and is kinda flooding the graphs:
![image](https://github.com/syssi/xiaomi_airpurifier/assets/14371247/2dae5c4d-8b2b-42b2-9215-79a328739ba6)
Personally I would prefer an update every 30 minutes.

**Comment by MasterSmurf** [comment]
I'm using the custom component `xiaomi_miio_airpurifier`. The `services.yaml` doesn't have a temperature sensor tho...

**Comment by syssi** [comment]
This is fine. Do you want to decrease the update interval of the temperature sensor or the integration at all? Both should be possible. The history of the sensor doesn't look good because the template sensor isn't configured a measurement. If you assign a proper `device_class` and `unit_of_measurement` you should see a graph here instead of colored segments.

**Comment by MasterSmurf** [comment]
Oh, thats a great addition! I've added `device_class` and `unit_of_measurement` to my `sensor.yaml`. Looking now like this:
```
- platform: template
  sensors:
    temperatur:
      friendly_name: 'Temperatur'
      device_class: temperature
      unit_of_measurement: °C
      value_template: "{{ state_attr('fan.xiaomi_air_humidifier','temperature') }}"
```
But I could **not** figure where to add `update_interval`. Actually I would like to prefer to decrease the interval of the integration at all. It is producing tons of useless data to me.

**Comment by syssi** [comment]
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Purifier 2
    host: 192.168.130.71
    token: b7c4a758c251955d2c24b1d9e41ce47d
    model: zhimi.airpurifier.m1
    update_interval: 15min
```

should do the job.

**Comment by MasterSmurf** [comment]
```
Configuration invalid!

Invalid config for [fan.xiaomi_miio_airpurifier]: [update_interval] is an invalid option for [fan.xiaomi_miio_airpurifier]. Check: fan.xiaomi_miio_airpurifier->update_interval. (See ?, line ?).
```
Currently running Home Assistant Core `2022.6.7` in docker
and xiaomi_airpurifier custom_component version: `2022.4.0.1`

I'll guess I have to upgrade. It broke some things last time I updated, but tinkering is fun😂

**Comment by syssi** [comment]
My information was just wrong. The parameter is called `scan_interval`. Please give it another try! :-)

**Comment by MasterSmurf** [comment]
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: 192.168.123.123
    token: kal6b1z9vvq9d5hjdvyk71k9hdmbw9gy
    model: zhimi.humidifier.ca4
    scan_interval: 900
```
Worked like a charm! Very nice! I'm still on my firmware version I mentioned before. Thank your very much @syssi !!
