### ISSUE TITLE
no Unique ID

### ISSUE THREAD

**Issue by Jokeru18** [syssi/xiaomi_airpurifier#342]
I can see the entities in the list but can't see the device or manage it. 

This entity ('sensor.airpurifier_aqi') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

Any ideas on what I did wrong?

**Comment by ildar170975** [comment]
My case:
I got a `dmaker.airfresh.t2017` fan.
Cannot assign this fan to a particular `area` since cannot assign a `unique_id` for the `fan` entity:
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: ...
    host: ...
    token: ...
    model: dmaker.airfresh.t2017
    unique_id: xxxxxxxxxxxxxxx
```

**Comment by ildar170975** [comment]
PR is issued: https://github.com/syssi/xiaomi_airpurifier/pull/360

**Comment by syssi** [comment]
If you don't pass the `model` parameter a unique id gets generated: 

```
fan:
  - platform: xiaomi_miio_airpurifier
    name: ...
    host: ...
    token: ...
```
