### ISSUE TITLE
Unsupported device: deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by lehtomar** [syssi/xiaomi_airpurifier#344]
Home Assistant log (Version 2023.8.1) gives following error when trying to setup humidifier 
2023-08-08 15:42:45.114 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by kiwimato** [comment]
it works for me under `fan`:
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi humidifier growroom
    host: 192.168.1.43
    token: db082e5fblablabla
    model: deerma.humidifier.jsq5
```
