### ISSUE TITLE
Add support for deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by mrbaloghakos** [syssi/xiaomi_airpurifier#381]
Xiaomi Smart Humidifier 2
https://www.mi.com/global/product/xiaomi-smart-humidifier-2/specs

**Comment by mrbaloghakos** [comment]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:162
integration: Xiaomi Miio (documentation, issues)
First occurred: 10:06:55 PM (1 occurrences)
Last logged: 10:06:55 PM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by michael-hermsen** [comment]
For me the same

Logger: homeassistant.components.xiaomi_miio
Bron: components/xiaomi_miio/__init__.py:162
integratie: Xiaomi Miio (documentatie, problemen)
Eerst voorgekomen: 08:34:47 (1 gebeurtenissen)
Laatst gelogd: 08:34:47

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by msmitka** [comment]
Same

**Comment by barnabas-kovacs** [comment]
Same here. Many Thanks!

**Comment by saschachina** [comment]
I don't think anyone will do anything here, they always refer to the custom component (https://github.com/syssi/xiaomi_airpurifier), see also #361

**Comment by syssi** [comment]
The device is supported here. What do you miss?

**Comment by saschachina** [comment]
> The device is supported here. What do you miss?

The .jsqs is supported not the .jsq2w

```
Logger: miio.miot_device
Quelle: /usr/local/lib/python3.12/site-packages/miio/miot_device.py:172
Erstmals aufgetreten: 16:54:59 (2 Vorkommnisse)
Zuletzt protokolliert: 16:55:29

Unable to find mapping for deerma.humidifier.jsq2w, falling back to deerma.humidifier.jsqs
```

**Comment by syssi** [comment]
If you use this custom component instead of the official one the device is supported.

**Comment by saschachina** [comment]
> If you use this custom component instead of the official one the device is supported.

Just so I understand, you say .jsq2w is supported by the custom component, then why do I get a warning in the logs like I showed before? I know that the device is not supported in the official integration so I am forced to use the custom component. 

Another question, why is it not possible to integrate the device in the official integration?

**Comment by syssi** [comment]
> Just so I understand, you say .jsq2w is supported by the custom component, then why do I get a warning in the logs like I showed before? I know that the device is not supported in the official integration so I am forced to use the custom component.

The users above are using the offical component:

> Source: components/xiaomi_miio/init.py:162

> Another question, why is it not possible to integrate the device in the official integration?

It is possible but it takes a lot of time per model and there are so many different models available. Furthermore it requires a lot of testing (using the real hardware in best case). In best case a owner of the device should take over and do the job.

**Comment by saschachina** [comment]
> > Just so I understand, you say .jsq2w is supported by the custom component, then why do I get a warning in the logs like I showed before? I know that the device is not supported in the official integration so I am forced to use the custom component.
> 
> The users above are using the offical component:
> 
> > Source: components/xiaomi_miio/init.py:162
> 
> > Another question, why is it not possible to integrate the device in the official integration?
> 
> It is possible but it takes a lot of time per model and there are so many different models available. Furthermore it requires a lot of testing (using the real hardware in best case). In best case a owner of the device should take over and do the job.

**First of all, i would like to thank you and everyone who invests time and effort in our smart home, i really appreciate it and am very grateful.** 

I also understand that a new device can't be integrated straight away because it requires a lot of work and someone has to have the device on site. 

The .jsqs already works, I don't know much about it but I think only minor adjustments are necessary for the .jsq2w. 

**Unfortunately I don't have the skills to read out anything, I can only support with testing.**

**Comment by franqenstein** [comment]
Also stuck with this problem, please help to fix )


deerma.humidifier.jsq2w

im also here if someone need to test something

**Comment by franqenstein** [comment]
@i4mr000t thank for your respones.

Plese tell me is there any way to make ha identify it as humidifier ? 

Now its working just as fan

**Comment by i4mr000t** [comment]
> @i4mr000t thank for your respones.
> 
> Plese tell me is there any way to make ha identify it as humidifier ?
> 
> Now its working just as fan

Your Welcome! :-)
Im not really sure what you mean but I think no because you cannot declare it as humidifier the integration doesnt allow this.

But maybe you can do some template sensor to get what you want. There are attributes in this fan entity.

For example:

```
platform: template
sensors:
  airpurifier_temperature:
    friendly_name: Xiaomi Smart Humidifier 2 Temperature
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.temperature }}"
    unit_of_measurement: "°C"
  airpurifier_humidity:
    friendly_name: Xiaomi Smart Humidifier 2 Humidity
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.humidity }}"
    unit_of_measurement: "%"
    icon_template: mdi:water-percent
  airpurifier_model:
    friendly_name: Xiaomi Smart Humidifier 2 Model
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.model }}"
  airpurifier_mode:
    friendly_name: Xiaomi Smart Humidifier 2 Mode
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.mode }}"
    icon_template: mdi:auto-mode
  airpurifier_buzzer:
    friendly_name: Xiaomi Smart Humidifier 2 Buzzer
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.buzzer }}"
    icon_template: mdi:volume-high
  airpurifier_target_humidity:
    friendly_name: Xiaomi Smart Humidifier 2 Target Humidity
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.target_humidity }}"
    icon_template: mdi:water-percent
    unit_of_measurement: "%"
  airpurifier_led:
    friendly_name: Xiaomi Smart Humidifier 2 LED
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.led }}"
    icon_template: mdi:lightbulb
  airpurifier_no_water:
    friendly_name: Xiaomi Smart Humidifier 2 No Water
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.no_water }}"
    icon_template: mdi:water
  airpurifier_water_tank_detached:
    friendly_name: Xiaomi Smart Humidifier 2 Watertank Detached
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.water_tank_detached }}"
    icon_template: mdi:storage-tank-outline
  airpurifier_water_wet_protection:
    friendly_name: Xiaomi Smart Humidifier 2 Water Protection
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.wet_protection }}"
    icon_template: mdi:water-off-outline
```
INFO:
`{{ states.<THIS_HAVE_TO_BE_YOUR_ENTITY_YOU_SET_BEFORE_IN_YOUR_CONFIGURATION.YAML>.attributes.temperature }}`

INFO 2:
I separated my template sensors in homeassistant from configuration.yaml. if you haven't you need to change the following code a little bit.

In configuration.yaml:
```
sensor:
  - platform: template
    sensors:
      airpurifier_aqi:
        friendly_name: Air Purifier Air Quality Index
        value_template: '{{ states.fan.xiaomi_air_purifier.attributes.aqi }}'          <---- You need to change that (read INFO)
        icon_template: mdi:weather-windy
```

Then you have different template sensors.

![image](https://github.com/user-attachments/assets/e079cb9a-7277-4b6b-b0fc-7aa54173b59c)

After that you need some actions to set for example the target humidity to 50% but as for now i didnt do it. 
I can put my code here later.
