### ISSUE TITLE
Please add support for deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by Deewde** [syssi/xiaomi_airpurifier#389]
deerma.humidifier.jsq2w please

**Comment by Schnabulation** [comment]
+1 for me. Seems that it's a new revision of the Smart Humidifier 2.

```
Logger: homeassistant.components.xiaomi_miio
Quelle: components/xiaomi_miio/__init__.py:164
Integration: Xiaomi Miio (Dokumentation, Probleme)
Erstmals aufgetreten: 15:23:40 (3 Vorkommnisse)
Zuletzt protokolliert: 15:38:10

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w
```

**Comment by i4mr000t** [comment]
You habe the wrong integration!

Install this one from HACS:
![image](https://github.com/user-attachments/assets/e047687c-9b75-46f5-b5b6-0bc44827b9e7)

than set your Humidifier in configuration.yaml to get the right token.

follow here:  https://github.com/syssi/xiaomi_airpurifier/issues/391

**Comment by kobatz82** [comment]
Hi, I have this humidifier also, I added all by the guide and from hacs but I only have mode and fan. I don't see temp or humidity so I can program him to turn off or on. Tnx for the hint and info.

**Comment by i4mr000t** [comment]
Hi please follow this guide: https://github.com/syssi/xiaomi_airpurifier/issues/381#issuecomment-2516289279

**Comment by kobatz82** [comment]
Sure, do I add all this in configuration yaml or other file? Thank you

**Comment by i4mr000t** [comment]
It depends on you if you want those template sensors.

If you have all your sensors in configuration.yaml add this:
```
sensor:
  - platform: template
    sensors:
      airpurifier_aqi:
        friendly_name: Air Purifier Air Quality Index
        value_template: '{{ states.fan.xiaomi_air_purifier.attributes.aqi }}'          <---- You need to change that (read INFO)
        icon_template: mdi:weather-windy
```
Keep going on with the list I provided as you like.

If you have separated your sensors like i did:
```
platform: template
sensors:
  airpurifier_temperature:
    friendly_name: Xiaomi Smart Humidifier 2 Temperature
    value_template: "{{ states.fan.xiaomi_smart_humidifier_2.attributes.temperature }}"
    unit_of_measurement: "°C"
```
Keep going on with the list I provided as you like.

**Comment by kobatz82** [comment]
It seems, I'm too stupid for this :( I have tried your instructions and no matter what I do I don't have simple sensor added for humidity. I only need one sensor for humidity so I can go forward creating automation. Spent hours and hours trying to add one sensor :(  Can you please tell me what to put where to get this sensor for humidity appearing in home assistant? Thank you very much in advance and sorry to bother you this much.

my current config:
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Smart Humidifier 2
    host: 192.168.2.84
    token: 234aa599adfab9b1860a9a7789a3cd67
    model: deerma.humidifier.jsq2w

**Comment by i4mr000t** [comment]
How does you configuration.yaml look like? Especially the Sensors Part?

should like look this for example:

`
…
sensor: !include_dir_list sensors/
…`

please post your entry for „Sensor“

**Comment by kobatz82** [comment]
For some reason I only have this in config yaml.
Tried adding your code in there with my entity and nothing happends.

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# configuration.yaml


fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Smart Humidifier 2
    host: 192.168.2.84
    token: 234aa599adfab9b1860a9a7789a3cd68
    model: deerma.humidifier.jsq2w

**Comment by i4mr000t** [comment]
Okay, no Problem.

please add this to your configuration.yaml

```
sensor:
  - platform: template
    sensors:
      xiaomi_smart_humidifier_2_humidity:
        friendly_name: Xiaomi Smart Humidifier 2 Humidity
        value_template: '{{ states.fan.xiaomi_smart_humidifier_2.attributes.humidity }}'
        icon: mdi:water
```

Reload your configuration.yaml or restart homeassistant.

After that you should have an entity called „Xiaomi Smart Humidifier 2 Humidity“

If not check your configuration yaml under dev Tools and post it here.

**Comment by kobatz82** [comment]
Ok. done and after reboot I got this error : Invalid config for 'sensor' from integration 'template' at configuration.yaml, line 28: 'icon' is an invalid option for 'template.sensor', check: sensors->xiaomi_smart_humidifier_2_humidity->icon
[home-assistant_2024-12-07T21-47-41.897Z.log](https://github.com/user-attachments/files/18049963/home-assistant_2024-12-07T21-47-41.897Z.log)

Tnx again for helping

**Comment by i4mr000t** [comment]
Yes it was my fault. Check the Code again.

I replaced „icon“ with „icon_template“

**Comment by kobatz82** [comment]
Works bud, tnx a ton!
Now my wife will not kill me of too much humidity in the room :)
![image](https://github.com/user-attachments/assets/27a1bfc1-adbc-485b-bb1c-1d5071453110)

**Comment by Andrey-Ysk** [comment]
> You habe the wrong integration!
> 
> Install this one from HACS: ![image](https://private-user-images.githubusercontent.com/39771894/392083150-e047687c-9b75-46f5-b5b6-0bc44827b9e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NTEyNDQsIm5iZiI6MTczNDY1MDk0NCwicGF0aCI6Ii8zOTc3MTg5NC8zOTIwODMxNTAtZTA0NzY4N2MtOWI3NS00NmY1LWI1YjYtMGJjNDQ4MjdiOWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDIzMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NzZlMmYzZDFlNGQ5ZjdjNmYwZWNhNDhlZGU5OWVmNmE2MmNjZmEyOGM3MGFlYmNiMDU1MmU4ZmMyOGNkODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8YQmiprjgSJH-Bjei8AO70uWXuAVBTNuryB2TKPRyio)
> 
> than set your Humidifier in configuration.yaml to get the right token.
> 
> follow here: #391

Thanks this work for me!
More info:
- Install HACS 
    https://www.hacs.xyz/docs/use/
- Get token from 
    https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor
- add to configuration.yaml
```
 fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Humidifier 2
    host: *humidifier_ip*
    token: *humidifier_token*
    model: deerma.humidifier.jsq2w
```
