### ISSUE TITLE
deerma.humidifier.jsq2w not working

### ISSUE THREAD

**Issue by i4mr000t** [syssi/xiaomi_airpurifier#391]
I added this to my configuration.yaml

```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Humidifier 2
    host: 192.168.178.123
    token: a6ed2xxxxxxxxxxxxxxxxxxxxxxxbf9960e8
    model: deerma.humidifier.jsq2w
```

Restarted Homeassistant and logs showing:

```
Logger: miio.miot_device
Quelle: /usr/local/lib/python3.12/site-packages/miio/miot_device.py:172
Erstmals aufgetreten: 16:46:58 (5 Vorkommnisse)
Zuletzt protokolliert: 16:49:19

Unable to find mapping for deerma.humidifier.jsq2w, falling back to deerma.humidifier.jsqs

```
