### ISSUE TITLE
Xiaomi Zero Fog Humidifier (shuii.humidifier.jsq001) support is missing

### ISSUE THREAD

**Issue by iromeo** [syssi/xiaomi_airpurifier#52]
The Xiaomi Zero Fog Humidifier (or "The fog free of humidifier" in MiHome app) has model ID `shuii.humidifier.jsq001`. I managed to get it's token and finally get an error `Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: shuii.humidifier.jsq001`

Could you please add support for it.

**Comment by iromeo** [comment]
I've filed an issue https://github.com/rytilahti/python-miio/issues/642 and the communication protocol seems to be clear now.

**Comment by iromeo** [comment]
Update: I've made a pull request to https://github.com/rytilahti/python-miio/issues/642 project and ready to implement the device support here.

**Comment by iromeo** [comment]
If anybody is interested in this device integration you could use my fork https://github.com/iromeo/xiaomi_airpurifier as HASS repository. Everything works ok

![image](https://user-images.githubusercontent.com/72933/78498861-be7cd900-7755-11ea-9341-264c98c2e544.png)

**Comment by Silent4831** [comment]
> Если кто-то заинтересован в интеграции этого устройства, вы можете использовать мою вилку [https://github.com/iromeo/xiaomi_airpurifier в ](https://github.com/iromeo/xiaomi_airpurifier)качестве хранилища Хасса. Все работает нормально
> 
> ![изображение](https://user-images.githubusercontent.com/72933/78498861-be7cd900-7755-11ea-9341-264c98c2e544.png)

Привет. Подскажи тупому, как заставить отображаться его отображаться в интерфейсе? Что в типе писать?
cards:
      - type: ????????
        entity: fan.deerma_humidifier_sck0a45
        model: deerma.humidifier.mjjsq

**Comment by iromeo** [comment]
@Silent4831 
> Привет. Подскажи тупому, как заставить отображаться его отображаться в интерфейсе? Что в типе писать?
> cards:
> - type: ????????
> entity: fan.deerma_humidifier_sck0a45
> model: deerma.humidifier.mjjsq

Hi Dmiry,
Sorry for the late reply, if it is still actual:
`configuration.yaml`
```yaml
fan:
  - platform: xiaomi_miio_airpurifier # xiaomi_miio
    name: 'Air Humidifier'
    host: !secret xiaomi_air_humidifier_ip
    model: shuii.humidifier.jsq001
    token: !secret xiaomi_air_humidifier  
```
Lovelace YAML config. No card available, but could be done manually:
```yaml
      - type: horizontal-stack
        cards:        
          - type: entities
            show_header_toggle: false
            entities:
              - entity: fan.air_humidifier
                secondary_info: last-changed  
              - entity: input_select.xiaomi_humidifier_mode
                secondary_info: last-changed 
              - entity: input_select.xiaomi_humidifier_brightness
              - entity: switch.xiaomi_humidifier_child_lock
              - entity: switch.xiaomi_humidifier_led
              - entity: switch.xiaomi_humidifier_buzzer
              - entity: sensor.humidifier_no_water
                secondary_info: last-changed 
```
and also in `configuration.yaml`:
```yaml
  # ------ Templates: Xiaomi Purifier features as switches
  - platform: template
    switches:
      xiaomi_airpurifier_led:
        friendly_name: "led"
        value_template: "{{ is_state_attr('fan.air_purifier', 'led', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_led_on
          data:
            entity_id: fan.air_purifier
        turn_off:
          service: xiaomi_miio.fan_set_led_off
          data:
            entity_id: fan.air_purifier
        icon_template: "mdi:lightbulb-outline"
      xiaomi_airpurifier_child_lock:
        friendly_name: "Child lock"
        value_template: "{{ is_state_attr('fan.air_purifier', 'child_lock', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_child_lock_on
          data:
            entity_id: fan.air_purifier
        turn_off:
          service: xiaomi_miio.fan_set_child_lock_off
          data:
            entity_id: fan.air_purifier
        icon_template: "mdi:lock-outline"

      xiaomi_airpurifier_buzzer:
        friendly_name: "Buzzer"
        value_template: "{{ is_state_attr('fan.air_purifier', 'buzzer', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_buzzer_on
          data:
            entity_id: fan.air_purifier
        turn_off:
          service: xiaomi_miio.fan_set_buzzer_off
          data:
            entity_id: fan.air_purifier
        icon_template: "mdi:volume-high"

      xiaomi_humidifier_led:
        friendly_name: "led"
        value_template: "{{ is_state_attr('fan.air_humidifier', 'led', true) }}"
        turn_on:
          service: fan.xiaomi_miio_set_led_on
          data:
            entity_id: fan.air_humidifier
        turn_off:
          service: fan.xiaomi_miio_set_led_off
          data:
            entity_id: fan.air_humidifier
        icon_template: "mdi:lightbulb-outline"

      xiaomi_humidifier_child_lock:
        friendly_name: "Child lock"
        value_template: "{{ is_state_attr('fan.air_humidifier', 'child_lock', true) }}"
        turn_on:
          service: fan.xiaomi_miio_set_child_lock_on
          data:
            entity_id: fan.air_humidifier
        turn_off:
          service: fan.xiaomi_miio_set_child_lock_off
          data:
            entity_id: fan.air_humidifier
        icon_template: "mdi:lock-outline"

      xiaomi_humidifier_buzzer:
        friendly_name: "Buzzer"
        value_template: "{{ is_state_attr('fan.air_humidifier', 'buzzer', true) }}"
        turn_on:
          service: fan.xiaomi_miio_set_buzzer_on
          data:
            entity_id: fan.air_humidifier
        turn_off:
          service: fan.xiaomi_miio_set_buzzer_off
          data:
            entity_id: fan.air_humidifier
        icon_template: "mdi:volume-high"
   sensors:
     humidifier_no_water:
        friendly_name: 'Увлажнитель Xiaomi - нет воды'
        # unit_of_measurement: '%'
        # entity_id:
        #   - sensor.time
        value_template: "{{ state_attr('fan.air_humidifier', 'no_water') }}"
        # icon_template: mdi:water-off
        icon_template: >-
          {% if state_attr('fan.air_humidifier', 'no_water') == "True" %}
          mdi:water-off
          {% else %}
          mdi:water-on
          {% endif %}

# Input field dialog
input_select:
     xiaomi_airpurifier_mode:
         name: Mode
         options:
          - Auto
          - Silent
          - Favorite
         icon: "mdi:animation-outline"
         
     xiaomi_humidifier_mode:
         name: Mode
         options:
          - Intelligent
          - Level1
          - Level2
          - Level3
          - Level4
         icon: "mdi:animation-outline"
    
         
     xiaomi_humidifier_brightness:
         name: Mode
         options:
          - 'Off'
          - Low
          - High
         icon:  "mdi:lightbulb-outline"
         
input_number:
    xiaomi_airpurifie_favorite_level:
        name: "Favorite level"
        initial: 0
        min: 0
        max: 14
        step: 1
        icon: "mdi:weather-windy"
        
  
```
