### ISSUE TITLE
Unsupported device found: deerma.humidifier.mjjsq

### ISSUE THREAD

**Issue by TheLastProject** [syssi/xiaomi_airpurifier#58]
Home Assistant commit 4d314ba4df, at time of writing the most recent commit of the master branch (https://github.com/home-assistant/core/commit/4d314ba4df7f0e797be80017a5643b05765f079f). I decided to run Home Assistant locally in a dev env on my Linux box to be able to debug the device not showing up in Home Assistant on my NAS to be sure it's not a token-related issue.

Feels weird to create this issue though because issue #40 and #43 exist which implies it should be supported?

Anyway, this is the error I got.

Logs:
```
2020-05-09 17:10:39 INFO (MainThread) [homeassistant.components.xiaomi_miio.fan] deerma.humidifier.mjjsq 2.0.4 esp8266 detected
2020-05-09 17:10:39 ERROR (MainThread) [homeassistant.components.xiaomi_miio.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpuri
fier/issues and provide the following data: deerma.humidifier.mjjsq
2020-05-09 17:10:39 INFO (MainThread) [homeassistant.setup] Setup of domain fan took 0.2 seconds.
```

Config:
```
fan:                                                                                                                              
    - platform: xiaomi_miio                                                                                                         
      host: 192.168.4.1                                                                                                             
      token: 3e249c038b4b8049bf3f810ff5560b0e                                                                                       
```

miiocli output:
```
$ miiocli device --ip 192.168.4.1 --token 3e249c038b4b8049bf3f810ff5560b0e info
Model: deerma.humidifier.mjjsq
Hardware version: esp8266
Firmware version: 2.0.4
Network: {'localIp': '192.168.4.1', 'mask': '255.255.255.0', 'gw': '192.168.4.1'}
AP: {'ssid': '', 'bssid': '00:00:00:00:00:00', 'rssi': 0, 'primary': 0}
```

Any way I can help debug this? I would love to get this working and thank you for all your work on this integration :)
