### ISSUE TITLE
Improve support of the Air Purifier Pro

### ISSUE THREAD

**Issue by syssi** [syssi/xiaomi_airpurifier#6]
- Reduce the feature set / number of services.
- Remove operation mode "idle".
- Debug set_favorite_level if needed. Operation unconfirmed.

**Comment by mattiasbrandt** [comment]
Is it a limitation that we can't use the 'State information':
temperature, humidity, aqi
as sensor entities?

**Comment by syssi** [comment]
Yes. The custom component doesn't provide a sensor per measurement/attribute. Just use the template platform if you want to access the attributes as a sensor. For example:

```
sensor:
  - platform: template
    sensors:
      airpurifier_aqi:
        friendly_name: Air Purifier Air Quality Index
        value_template: '{{ states.fan.xiaomi_air_purifier.attributes.aqi }}'
```
