### ISSUE TITLE
How to install this integration? 

### ISSUE THREAD

**Issue by a-x-** [syssi/xiaomi_airpurifier#61]
I cannot find it in hacs integrations

UPD: can you explain installation in the readme or add it into HACS registry?

**Comment by fufar** [comment]
for me like that

in configuration.yaml

```
fan:
  - platform: xiaomi_miio_airpurifier
    host: 192.168.1.XX
    token: 00XXXXXXXXXXXXXXXXXXXXXXXb
    name: humidifier
    model: deerma.humidifier.mjjsq
```
