### ISSUE TITLE
zhimi.airpurifier.va1 support please

### ISSUE THREAD

**Issue by anschein** [syssi/xiaomi_airpurifier#79]
zhimi.airpurifier.va1 as xiaomi airpurifier PROH
please add this device

**Comment by anschein** [comment]
just See if there is progress，Is there anything i can help for this device？

**Comment by latel** [comment]
any progress here?

**Comment by timdj** [comment]
You can get it to at least partly work using following config and overwriting the model id.
```
fan:
  - platform: xiaomi_miio
    host: XXX.XXX.XXX.XXX
    token: XXXXXXXXXXXXXXXXXXXXXXX
    model: zhimi.airpurifier.mb3
    name: "Air purifier living room"
```
