### ISSUE TITLE
How to setup a switch template to call some services

### ISSUE THREAD

**Issue by 4ertik131** [syssi/xiaomi_airpurifier#85]
Good day ! to begin with, I want to express my deep gratitude to the developers of the add-on ,, xiaomi_airpurifier ,, and express hope that the project will continue to develop! 

now about the topic of the post:

according to the instructions in README.md I installed the add-on ,, xiaomi_airpurifier ,, and set up the Air Humidifier MJJSQ .

![Screenshot_2020-10-30-22-22-14-748_com android chrome](https://user-images.githubusercontent.com/73563169/97748364-6dbc3b80-1afe-11eb-9d20-1b2a11e700a6.jpg)

after studying the post

https://community.home-assistant.io/t/xiaomi-air-purifier-show-all-sensors-and-switches-in-ui-and-homekit/121786

unsuccessfully trying to add on / off lights, need your help.

here is my configuration.yaml file

```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: 192.168.1.191
    token: e23dfbcf44f8aeea9e82d409c9c21e2b
    model: deerma.humidifier.mjjsq

sensor:
  - platform: template
    sensors:
      airpurifier_led:
        friendly_name: Air Purifier led Index
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.led }}'
      airhumidifier_temperature:
        friendly_name: Air Humidifier Temperature
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.temperature }}'
        unit_of_measurement: '°C'
      airhumidifier_humidity:
        friendly_name: Air Humidifier Humidity
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.humidity }}'
        unit_of_measurement: '%'
      airhumidifier_mode:
        friendly_name: Air Humidifier mode
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.mode }}'
      airhumidifier_target_humidity:
        friendly_name: Air Humidifier Target Humidity
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}'
        unit_of_measurement: '%'   
      airhumidifier_model:
        friendly_name: Air Humidifier model
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.model }}'
```

here is an example of what I am trying to modify

```
switch:
  - platform: template
    switches:
      xiaomi_airpurifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.xiaomi_miio_device', 'led', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_led_on
          data:
            entity_id: fan.xiaomi_miio_device
        turn_off:
          service: xiaomi_miio.fan_set_led_off
          data:
            entity_id: fan.xiaomi_miio_device
        icon_template: "mdi:lightbulb-outline"
```

**Comment by syssi** [comment]
Could you inspect your home-assistant.log and provide the error messages?

**Comment by 4ertik131** [comment]
error messages do not appear! (both in the log and in pop-up messages)

![IMG_20201031_125504](https://user-images.githubusercontent.com/73563169/97776426-e52eb100-1b78-11eb-89db-08d7ca5710c3.jpg)

when you press the button ,, led ,, nothing happens. (no response from humidifier)

**Comment by syssi** [comment]
Plese replace "true" with "True". This template switch works for my air purifier:

```
switch:
  - platform: template
    switches:
      xiaomi_airpurifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.air_purifier_2', 'led', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_led_on
          data:
            entity_id: fan.air_purifier_2
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_led_off
          data:
            entity_id: fan.air_purifier_2
        icon_template: "mdi:lightbulb-outline"
```

**Comment by 4ertik131** [comment]
> Plese replace "true" with "True". This template switch works for my air purifier:
> 
> ```
> switch:
>   - platform: template
>     switches:
>       xiaomi_airpurifier_led:
>         friendly_name: "LED"
>         value_template: "{{ is_state_attr('fan.air_purifier_2', 'led', True) }}"
>         turn_on:
>           service: xiaomi_miio_airpurifier.fan_set_led_on
>           data:
>             entity_id: fan.air_purifier_2
>         turn_off:
>           service: xiaomi_miio_airpurifier.fan_set_led_off
>           data:
>             entity_id: fan.air_purifier_2
>         icon_template: "mdi:lightbulb-outline"
> ```

fixed, still does not work.

how to find out the correct
entity_id: ????
for my device.

**Comment by syssi** [comment]
Just browse this list: http://localhost:8123/developer-tools/state

**Comment by 4ertik131** [comment]
hurray, it worked!

![IMG_20201031_144726](https://user-images.githubusercontent.com/73563169/97778413-14005380-1b88-11eb-86c9-f1b9c341977f.jpg)

,,,
switch:
  # 
  - platform: template
    switches:
       xiaomi_airpurifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.xiaomi_air_humidifier', 'led', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_led_on
          data:
            entity_id: fan.xiaomi_air_humidifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_led_off
          data:
            entity_id: fan.xiaomi_air_humidifier
        icon_template: "mdi:lightbulb-outline"
,,,        
Thank you for your help, I will add all the buttons and switches to the config in this topic.

**Comment by syssi** [comment]
If you like, you could setup templates for every feature of your device. A target humidify slider would be nice.

**Comment by 4ertik131** [comment]
> If you like, you could setup templates for every feature of your device. A target humidify slider would be nice.

do you have an example configuration.yaml with 
configured humidify slider (0 ... 90% humidity)
and
mode slider (Low, Medium, High, Humidity)?

**Comment by syssi** [comment]
You could adopt this one: https://community.home-assistant.io/t/xiaomi-mi-wifi-plug-air-purifier/16189/372

**Comment by syssi** [comment]
This works for my air purifier entity:

```
input_select:
  airpurifier_mode:
    name: Mode
    options:
     - Auto
     - Silent
     - Favorite
     - Idle


automation:
  - id: xiaomi_mode
    alias: Xiaomi Mode
    trigger:
      platform: state
      entity_id: input_select.airpurifier_mode
    action:
      - service: fan.set_speed
        data_template:
          entity_id: fan.air_purifier_2
          speed: '{{ states.input_select.airpurifier_mode.state }}'
```

**Comment by 4ertik131** [comment]
> Это работает для моего очистителя воздуха:
> 
> ```
> input_select:
>   airpurifier_mode:
>     name: Mode
>     options:
>      - Auto
>      - Silent
>      - Favorite
>      - Idle
> 
> 
> automation:
>   - id: xiaomi_mode
>     alias: Xiaomi Mode
>     trigger:
>       platform: state
>       entity_id: input_select.airpurifier_mode
>     action:
>       - service: fan.set_speed
>         data_template:
>           entity_id: fan.air_purifier_2
>           speed: '{{ states.input_select.airpurifier_mode.state }}'
> ```
thanks for the example! I improved it to get an update online (when switching modes mechanically on the humidifier itself, the mode status in the Homeassistant changes)
```
input_select:
  airpurifier_mode:
    name: Mode
    options:
     - Low
     - Medium
     - High
     - Humidity
        
- alias: Xiaomi Mode
  trigger:
    entity_id: input_select.airpurifier_mode
    platform: state
  action:
    service: fan.set_speed
    data_template:
      entity_id: fan.xiaomi_air_humidifier
      speed: '{{ states.input_select.airpurifier_mode.state }}'
- alias: xiaomi_mode
  trigger:
    platform: state
    entity_id: fan.xiaomi_air_humidifier
  action:
    service: input_select.select_option
    entity_id: input_select.airpurifier_mode
    data_template:
      option: '{{ states.fan.xiaomi_air_humidifier.attributes.speed }}'
```


i started setting target_humidity and faced such problem -
target_humidity does not display values. possible error in the code?
```
      airhumidifier_target_humidity:
        friendly_name: Air Humidifier Target Humidity
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}'
        unit_of_measurement: '%'   
```

**Comment by syssi** [comment]
Are you able to control the `target_humidity` in general via the service? Just the feedback (attribute) is missing for both devices?

**Comment by syssi** [comment]
@4ertik131 The `target_humidity` is available now if you update the custom component to the `develop` branch.

**Comment by 4ertik131** [comment]
> @ 4ertik131 Теперь `target_humidity`доступен, если вы обновите пользовательский компонент в `develop`ветке.

thanks. everything works, i tested on both humidifiers.
![IMG_20201101_221054](https://user-images.githubusercontent.com/73563169/97812051-b9521f00-1c8f-11eb-9e63-3a90d69f3112.jpg)

**Comment by 4ertik131** [comment]
@syssi 
do you have a use case for the service?
   xiaomi_miio_airpurifier.fan_set_target_humidity

**Comment by syssi** [comment]
Do you like to provide an `input_slider` or `input_select` example to control the target temperature? I would like to add it to the docs.

**Comment by 4ertik131** [comment]
@syssi 
input_slider the best thing

**Comment by 4ertik131** [comment]
> Вы хотели бы предоставить ли `input_slider`или `input_select`пример для управления целевой влажности? Хочу добавить в документацию.



> Do you like to provide an `input_slider` or `input_select` example to control the target humidity? I would like to add it to the docs.

cheerful morning !

there is news about adding use cases xiaomi_miio_airpurifier.fan_set_target_humidity ? 
all my attempts to use examples from internet search have failed  :weary:

**Comment by syssi** [comment]
Could you tell me the supported target humidities (`30`, `40`, `50`,...) of your devices?

**Comment by syssi** [comment]
Please adopt this example for your needs:

```
input_number:
  airpurifier_favorite_level:
    name: Favorite Level
    initial: 1
    min: 0
    max: 16
    step: 1

automation:
  - alias: Airpurifier Favorite Level Slider
    trigger:
      platform: state
      entity_id: input_number.airpurifier_favorite_level
    action:
      - service: xiaomi_miio_airpurifier.fan_set_favorite_level
        data_template:
          entity_id: fan.air_purifier_2
          level: '{{ states.input_number.airpurifier_favorite_level.state }}'
```

Your feedback loop is missing in this example.

**Comment by syssi** [comment]
If've added a full-featured input number example to the docs: https://github.com/syssi/xiaomi_airpurifier#input-number-example

You want to use the `xiaomi_miio_airpurifier.fan_set_target_humidity` service instead an monitor the `target_humidity` attribute.

**Comment by syssi** [comment]
I think this configuration should to the job:

```
input_number:
  airhumidifier_target_humidity:
    name: Target humidity
    min: 0
    max: 99
    step: 1

automation:
  - alias: Select target humidity by slider
    trigger:
      platform: state
      entity_id: input_number.airhumidifier_target_humidity
    action:
      - service: xiaomi_miio_airpurifier.fan_set_target_humidity
        data_template:
          entity_id: fan.xiaomi_air_humidifier
          humidity: '{{ states.input_number.airhumidifier_target_humidity.state|int }}'

  - alias: Monitor target humidity and update slider
    trigger:
      platform: state
      entity_id: fan.xiaomi_air_humidifier
    action:
      service: input_number.set_value
      entity_id: input_number.airhumidifier_target_humidity
      data_template:
        value: '{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}'
```

**Comment by 4ertik131** [comment]
> Я думаю, что эта конфигурация должна работать:
> 
> ```
> input_number:
>   airhumidifier_target_humidity:
>     name: Target humidity
>     min: 0
>     max: 99
>     step: 1
> 
> automation:
>   - alias: Select target humidity by slider
>     trigger:
>       platform: state
>       entity_id: input_number.airhumidifier_target_humidity
>     action:
>       - service: xiaomi_miio_airpurifier.fan_set_target_humidity
>         data_template:
>           entity_id: fan.xiaomi_air_humidifier
>           humidity: '{{ states.input_number.airhumidifier_target_humidity.state|int }}'
> 
>   - alias: Monitor target humidity and update slider
>     trigger:
>       platform: state
>       entity_id: fan.xiaomi_air_humidifier
>     action:
>       service: input_number.set_value
>       entity_id: input_number.airhumidifier_target_humidity
>       data_template:
>         value: '{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}'
> ```

Thank you very much for the work done.

I needed time to check everything for performance.

everything works correctly except for feedback.

the feedback is not responsive.
![IMG_20201104_140927](https://user-images.githubusercontent.com/73563169/98104423-7c607500-1ea7-11eb-884b-5f283b634deb.jpg)

**Comment by syssi** [comment]
```
      platform: state
      entity_id: fan.xiaomi_air_humidifier
```

The trigger isn't correct. We are monitoring the `state` of the device. We should monitor the target humidity attribute instead.

**Comment by 4ertik131** [comment]
> ```
>       platform: state
>       entity_id: fan.xiaomi_air_humidifier
> ```
> 
> Триггер неправильный. Мы следим за работой `state`устройства. Вместо этого мы должны контролировать целевой атрибут влажности.

```
 alias: Monitor target humidity and update slider
  trigger:
      platform: state
      entity_id:  
      #sensor.airhumidifier_target_humidity
      #input_number.airhumidifier_target_humidity
      #fan.xiaomi_air_humidifier
```
I've tried these options. no one works. no feedback(

**Comment by syssi** [comment]
Please try this one:

```
sensor:
  - platform: template
    sensors:
      airhumidifier_target_humidity:
        friendly_name: Target humidity
        value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent

input_number:
  airhumidifier_target_humidity:
    name: Target humidity
    min: 0
    max: 99
    step: 1

automation:
  - alias: Select target humidity by slider
    trigger:
      platform: state
      entity_id: input_number.airhumidifier_target_humidity
    action:
      - service: xiaomi_miio_airpurifier.fan_set_target_humidity
        data_template:
          entity_id: fan.xiaomi_air_humidifier
          humidity: '{{ states.input_number.airhumidifier_target_humidity.state|int }}'

  - alias: Monitor target humidity and update slider
    trigger:
      platform: state
      entity_id: sensor.airhumidifier_target_humidity
    action:
      service: input_number.set_value
      entity_id: input_number.airhumidifier_target_humidity
      data_template:
        value: '{{ states.fan.xiaomi_air_humidifier.attributes.target_humidity }}'
```

The `target_humidity` attribute is exposed as template sensor here. So we can monitor the state of the sensor.
