### ISSUE TITLE
Cannot import name 'AirHumidifierMiot' from 'miio'" - workaround

### ISSUE THREAD

**Issue by Morph26** [syssi/xiaomi_airpurifier#98]
Get error, when check config:
`Platform error fan.xiaomi_miio_airpurifier - cannot import name 'AirHumidifierMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)`

Error appears, when adding to configuration.yaml:
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: mi_humidifier_child
    host: 192.168.x.xx
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    model: deerma.humidifier.mjjsq
```
                        
HA supervised. Xiaomi Mi Air Purifier, Air Humidifier, Air Fresh and Pedestal Fan Integration installed via HACS.
System info:
```
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.72
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/Moscow
version | 0.117.4
virtualenv | false

```
